name: Bug report
assignees: [Akysooo]
description: Report un bug
title: '[Bug]: '
labels:
  - bug
  - ' triage'
body:
  - type: input
    id: pseudo
    attributes:
      label: Pseudo InGame
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Que s'est-il passé ?
      description: Dites-nous ce qui est arrivé
    validations:
      required: true
  - type: input
    id: rec
    attributes:
      label: Rec
    validations:
      required: true
  - type: textarea
    id: what-should-happened
    attributes:
      label: 'Qu''aurait-il dû arriver ?'
  - type: textarea
    id: log
    attributes:
      label: LOG
      description: Si vous avez des logs à nous fournir, c'est ici !
